# Use postgres/example user/password credentials
version: '3.9'

services:

  app:
    image: 'menu'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=$MENU_DATABASE_USER
      - POSTGRES_PASSWORD=$MENU_DATABASE_PASSWORD
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/$MENU_DATABASE_NAME
      - SPRING_DATASOURCE_USERNAME=$MENU_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$MENU_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "$LOCAL_PORT:8080"

  db:
    image: postgres:16-alpine3.21
    restart: always
    ports:
      - "5433:5432"
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${MENU_DATABASE_USER}
      POSTGRES_PASSWORD: ${MENU_DATABASE_PASSWORD}
      POSTGRES_DB: ${MENU_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8081:80/tcp"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${MENU_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${MENU_PGADMIN_PASSWORD}

volumes:
  pgadmin:
  db: