# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:16-alpine3.21
    restart: always
    ports:
      - "5433:5432"
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${MENU_DATABASE_USER}
      POSTGRES_PASSWORD: ${MENU_DATABASE_PASSWORD}
      POSTGRES_DB: ${MENU_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8081:80/tcp"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${MENU_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${MENU_PGADMIN_PASSWORD}

volumes:
  pgadmin:
  db: